"""DB rework.

Revision ID: 00938a06625a
Revises:
Create Date: 2025-04-30 06:46:45.643200+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00938a06625a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role = op.create_table(
        "role",
        sa.Column("id", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.bulk_insert(
        role,
        [
            {
                'id': 1,
                'name': 'admin',
                'description': 'Has all the rights.',
            },
            {
                'id': 2,
                'name': 'priveleged',
                'description': (
                    'Has all the rights, but cannot change the project settings.'
                ),
            },
            {
                'id': 3,
                'name': 'default',
                'description': (
                    'Can change the status of the task to which '
                    'he is assigned and leave comments under it.'
                ),
            },
        ]
    )

    task_priority = op.create_table(
        "task_priority",
        sa.Column("id", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), nullable=False),
        sa.Column("weight", sa.SMALLINT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_priority")),
    )
    op.create_index(op.f("ix_task_priority_id"), "task_priority", ["id"], unique=False)
    op.bulk_insert(
        task_priority,
        [
            {
                'id': 1,
                'name': 'Low',
                'weight': 1,
            },
            {
                'id': 2,
                'name': 'Medium',
                'weight': 2,
            },
            {
                'id': 3,
                'name': 'High',
                'weight': 3,
            },
            {
                'id': 4,
                'name': 'Critical',
                'weight': 4,
            },
        ]
    )

    task_status = op.create_table(
        "task_status",
        sa.Column("id", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_status")),
    )
    op.create_index(op.f("ix_task_status_id"), "task_status", ["id"], unique=False)
    op.bulk_insert(
        task_status,
        [
            {
                'id': 1,
                'name': 'Not assign',
            },
            {
                'id': 2,
                'name': 'To do',
            },
            {
                'id': 3,
                'name': 'In progress',
            },
            {
                'id': 4,
                'name': 'Done',
            },
        ]
    )

    task_type = op.create_table(
        "task_type",
        sa.Column("id", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_type")),
    )
    op.create_index(op.f("ix_task_type_id"), "task_type", ["id"], unique=False)
    op.bulk_insert(
        task_type,
        [
            {
                'id': 1,
                'name': 'Bug',
            },
            {
                'id': 2,
                'name': 'Fix',
            },
            {
                'id': 3,
                'name': 'Feature',
            },
            {
                'id': 4,
                'name': 'Misc',
            },
        ]
    )

    op.create_table(
        "user",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("username", sa.VARCHAR(length=50), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=150), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=128), nullable=False),
        sa.Column("email", sa.VARCHAR(length=254), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)

    op.create_table(
        "project",
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("key", sa.VARCHAR(length=10), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("fk_project_creator_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("key", "creator_id", name=op.f("uq_project_key")),
    )
    op.create_index(
        "ix_project_fts",
        "project",
        [sa.literal_column("to_tsvector('english', name || ' ' || key)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_project_id"), "project", ["id"], unique=False)

    op.create_table(
        "project_invite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.SMALLINT(), nullable=False),
        sa.Column("invite_token", sa.VARCHAR(length=255), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("fk_project_invite_creator_id_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_invite_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_project_invite_role_id_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_invite")),
    )
    op.create_index(
        op.f("ix_project_invite_id"), "project_invite", ["id"], unique=False
    )

    op.create_table(
        "task",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("type_id", sa.SMALLINT(), nullable=False),
        sa.Column("priority_id", sa.SMALLINT(), nullable=False),
        sa.Column("status_id", sa.SMALLINT(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
            name=op.f("fk_task_assignee_id_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("fk_task_creator_id_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["task_priority.id"],
            name=op.f("fk_task_priority_id_task_priority"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_task_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["task_status.id"],
            name=op.f("fk_task_status_id_task_status"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["task_type.id"],
            name=op.f("fk_task_type_id_task_type"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
        sa.UniqueConstraint("name", "project_id", name=op.f("uq_task_name")),
    )
    op.create_index(
        "ix_task_fts",
        "task",
        [sa.literal_column("to_tsvector('english', name || ' ' || description)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_task_id"), "task", ["id"], unique=False)

    op.create_table(
        "user_project_role",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.SMALLINT(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_user_project_role_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_user_project_role_role_id_role"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_project_role_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "project_id", "role_id", name=op.f("pk_user_project_role")
        ),
    )

    op.create_table(
        "task_comment",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name=op.f("fk_task_comment_task_id_task"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_task_comment_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_comment")),
    )
    op.create_index(op.f("ix_task_comment_id"), "task_comment", ["id"], unique=False)

    op.create_table(
        "task_history",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("changed_field", sa.VARCHAR(length=255), nullable=False),
        sa.Column("old_value", sa.VARCHAR(length=255), nullable=False),
        sa.Column("new_value", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["user.id"],
            name=op.f("fk_task_history_changed_by_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name=op.f("fk_task_history_task_id_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_history")),
    )
    op.create_index(op.f("ix_task_history_id"), "task_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_history_id"), table_name="task_history")
    op.drop_table("task_history")
    op.drop_index(op.f("ix_task_comment_id"), table_name="task_comment")
    op.drop_table("task_comment")
    op.drop_table("user_project_role")
    op.drop_index(op.f("ix_task_id"), table_name="task")
    op.drop_index("ix_task_fts", table_name="task", postgresql_using="gin")
    op.drop_table("task")
    op.drop_index(op.f("ix_project_invite_id"), table_name="project_invite")
    op.drop_table("project_invite")
    op.drop_index(op.f("ix_project_id"), table_name="project")
    op.drop_index("ix_project_fts", table_name="project", postgresql_using="gin")
    op.drop_table("project")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_task_type_id"), table_name="task_type")
    op.drop_table("task_type")
    op.drop_index(op.f("ix_task_status_id"), table_name="task_status")
    op.drop_table("task_status")
    op.drop_index(op.f("ix_task_priority_id"), table_name="task_priority")
    op.drop_table("task_priority")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
