"""Remove is_staff column from auth_user table

Revision ID: 3a72eced7d4d
Revises: 9673fb3c1bb3
Create Date: 2024-10-01 11:19:33.622926+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a72eced7d4d'
down_revision: Union[str, None] = '9673fb3c1bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'is_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('is_staff', sa.BOOLEAN, nullable=False, default=False))
    # ### end Alembic commands ###
