"""Rename 'starred' to 'favorite' and remove a unique name constraint in project table.

Revision ID: 4389da4f3d25
Revises: 443d30f0c48c
Create Date: 2025-01-21 10:42:26.161619+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4389da4f3d25'
down_revision: Union[str, None] = '443d30f0c48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('favorite', sa.Boolean(), nullable=True))
    op.drop_constraint('project_unique_name', 'project', type_='unique')
    op.drop_column('project', 'starred')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('starred', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('project_unique_name', 'project', ['author_id', 'name'])
    op.drop_column('project', 'favorite')
    # ### end Alembic commands ###
